export * from './ingredients-slice';
export * from './burger-constructor-slice';
export * from './order-slice';
export * from './feed-slice';
export * from './user-orders-slice';
export * from './user-slice';
export { default as ingredientsReducer } from './ingredients-slice';
export { default as burgerConstructorReducer } from './burger-constructor-slice';
export { default as orderReducer } from './order-slice';
export { default as feedReducer } from './feed-slice';
export { default as userOrdersReducer } from './user-orders-slice';
export { default as userReducer } from './user-slice';
